import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import ThemeRegistry from './components/ThemeRegistry/ThemeRegistry'
import Container from '@mui/material/Container'
import NavBar from './components/NavBar'
import Header from './components/Header'

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Trello App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ThemeRegistry>
          <Container
            disableGutters
            maxWidth={false}
            sx={{ maxHeight: '100vh', overflowY: 'hidden' }}
          >
            <Header />
            <NavBar />
            {children}
          </Container>
        </ThemeRegistry>
      </body>
    </html>
  )
}
